services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: vllm-server
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 480s

    networks:
      - vllm-net

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0
      - VLLM_FLASHINFER_AUTOTUNE_CACHE_DIR="/tmp/flashinfer_autotune_cache"

      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MODEL_NAME=nvidia/Qwen3.6-27B-NVFP4
      - ENABLE_API_KEY=true
      - DTYPE=auto
      - SAFETENSORS_LOAD_STRATEGY=prefetch
      - TP_SIZE=1
      - ATTENTION_BACKEND=flashinfer
      - PERFORMANCE_MODE=interactivity
      - LANGUAGE_MODEL_ONLY=true
      - SKIP_MM_PROFILING=true
      - KV_CACHE_DTYPE=fp8_e4m3
      - GPU_MEMORY_UTILIZATION=0.92
      - MAX_MODEL_LEN=131072
      - MAX_NUM_SEQS=1
      - MAX_NUM_BATCHED_TOKENS=6144
      - ENABLE_CHUNKED_PREFILL=true
      - ENABLE_PREFIX_CACHING=true
      - ENABLE_HYBRID_KV_CACHE_MANAGER=true
      - REASONING_PARSER=qwen3
      - DEFAULT_ENABLE_THINKING=true
      - ENABLE_AUTO_TOOL_CHOICE=true
      - TOOL_CALL_PARSER=qwen3_coder
      - QUANTIZATION=modelopt
      - ENABLE_MTP=true
      - MTP_NUM_SPECULATIVE_TOKENS=3
      - TRUST_REMOTE_CODE=true
      - ENABLE_PROMPT_TOKENS_DETAILS=true
      - ENABLE_REQUEST_METRICS=true
      - PORT=8000
      # --- HuggingFace ---
      - HF_TOKEN=${HF_TOKEN}

    volumes:
      - hf-cache:/root/.cache/huggingface
      - vllm-keys:/root/.vllm-key

    ports:
      - "1235:8000"

    shm_size: "16gb"
    ipc: host

networks:
  vllm-net:
    attachable: true

volumes:
  hf-cache:
  vllm-keys:
